//
// ArtworksAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ArtworksAPI {

    /**
     Artworks List
     
     - parameter skip: (query) Number of page 
     - parameter limit: (query) Limit of artworks by page 
     - parameter hasImage: (query) Filter to return only artworks that have a web image asset 
     - returns: ArtworksList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func everythingGet(skip: Int, limit: Int, hasImage: Int) async throws -> ArtworksList {
        return try await everythingGetWithRequestBuilder(skip: skip, limit: limit, hasImage: hasImage).execute().body
    }

    /**
     Artworks List
     - GET /artworks
     - parameter skip: (query) Number of page 
     - parameter limit: (query) Limit of artworks by page 
     - parameter hasImage: (query) Filter to return only artworks that have a web image asset 
     - returns: RequestBuilder<ArtworksList> 
     */
    open class func everythingGetWithRequestBuilder(skip: Int, limit: Int, hasImage: Int) -> RequestBuilder<ArtworksList> {
        let localVariablePath = "/artworks"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "skip": (wrappedValue: skip.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit.encodeToJSON(), isExplode: true),
            "has_image": (wrappedValue: hasImage.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ArtworksList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
