//
// ArtworkImages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArtworkImages: Codable, JSONEncodable, Hashable {

    public var web: ArtworkImagesWeb?
    public var print: ArtworkImagesPrint?
    public var full: ArtworkImagesPrint?

    public init(web: ArtworkImagesWeb? = nil, print: ArtworkImagesPrint? = nil, full: ArtworkImagesPrint? = nil) {
        self.web = web
        self.print = print
        self.full = full
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case web
        case print
        case full
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(web, forKey: .web)
        try container.encodeIfPresent(print, forKey: .print)
        try container.encodeIfPresent(full, forKey: .full)
    }
}

